name: Upload Release to MirrorChyan

# 触发条件：手动触发或版本发布后
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  mirrorchyan:
    runs-on: macos-latest

    steps:
      # 下载 Release 包
      - name: Download Release
        uses: robinraju/release-downloader@v1
        id: download
        with:
          repository: moesnow/March7thAssistant
          fileName: "*full.7z"
          latest: true
          out-file-path: "March7thAssistant"
          extract: false

      - name: Upload to MirrorChyan
        run: |
          curl --location --request POST 'https://mirrorc.top/api/resources/${{ github.event.repository.name }}/versions' \
            --header 'Authorization:${{ secrets.MirrorChyanUploadToken }}' \
            --form 'name="${{steps.download.outputs.tag_name}}"' \
            --form 'file=@"${{ fromJson(steps.download.outputs.downloaded_files)[0] }}"'
